include ~/.config/batcave/generated/kitty-colors.conf

font_family JetBrainsMono Nerd Font
font_size 12.5

background_opacity 0.88
confirm_os_window_close 0

window_padding_width 12

enable_audio_bell no

cursor_shape block
cursor_blink_interval 0

background #08090c
foreground #c8cbd1

selection_background #1c2631
selection_foreground #e5e7eb

active_border_color #607b96
inactive_border_color #15181d

window_border_width 1px
