source = ~/.config/batcave/generated/hyprlock-colors.conf
general {
    hide_cursor = true
    ignore_empty_input = false
}

background {
    monitor =
    path = ~/.cache/batcave/current-wallpaper

    blur_passes = 3
    blur_size = 5

    brightness = 0.35
    contrast = 0.90
}

label {
    monitor =

    text = "G O T H A M"

    color = $muted

    font_size = 14
    font_family = JetBrainsMono Nerd Font

    position = 0, 140

    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:1000] date '+%I:%M %p'

    color = $fg

    font_size = 76
    font_family = JetBrainsMono Nerd Font

    position = 0, 30

    halign = center
    valign = center
}

label {
    monitor =

    text = "BATCAVE"

    color = $accent

    font_size = 12
    font_family = JetBrainsMono Nerd Font

    position = 0, -70

    halign = center
    valign = center
}

input-field {
    monitor =

    size = 280, 52

    outline_thickness = 1

    inner_color = rgba(5, 7, 10, 0.75)
    outer_color = $border
    font_color = $fg

    fade_on_empty = false

    position = 0, -135

    halign = center
    valign = center
}